env:
  global:
    - secure: ffm5mxyfeQFAX8pukIrKnYTboB8F3/Z4BYRoDHfsWdAjoa+jhpx4cCgtnmUYSz9TYOy4z/LARMtGq9hDyh3j8kQFP4sQkHpruqxPjPmQRCjarz6ySTmEio62zxU2scjI/xl4Y5yDColJJBWOGNYFKldOknk/fpQEEbMe1k7op8Y=
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
script:
  - make all
  - make check
  - make doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
